// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdS-e7ddZGSyd8Oj04w75MbBjzpmiTTxQ',
    appId: '1:767939049500:web:5fa8919de437d418e0c7d9',
    messagingSenderId: '767939049500',
    projectId: 'dice-master-36257',
    authDomain: 'dice-master-36257.firebaseapp.com',
    storageBucket: 'dice-master-36257.firebasestorage.app',
    measurementId: 'G-KHX7PQ06K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Z1FKB6OH2Wnv7sZcr0ERf1aUlExJr8Q',
    appId: '1:767939049500:android:ec39c725ac0ea95fe0c7d9',
    messagingSenderId: '767939049500',
    projectId: 'dice-master-36257',
    storageBucket: 'dice-master-36257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi0AXxslSmmixWb3r4INLIBS1i3mNeeM8',
    appId: '1:767939049500:ios:7ef7c4302b872f12e0c7d9',
    messagingSenderId: '767939049500',
    projectId: 'dice-master-36257',
    storageBucket: 'dice-master-36257.firebasestorage.app',
    iosBundleId: 'com.example.diceMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi0AXxslSmmixWb3r4INLIBS1i3mNeeM8',
    appId: '1:767939049500:ios:7ef7c4302b872f12e0c7d9',
    messagingSenderId: '767939049500',
    projectId: 'dice-master-36257',
    storageBucket: 'dice-master-36257.firebasestorage.app',
    iosBundleId: 'com.example.diceMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdS-e7ddZGSyd8Oj04w75MbBjzpmiTTxQ',
    appId: '1:767939049500:web:9ed85f972f54771de0c7d9',
    messagingSenderId: '767939049500',
    projectId: 'dice-master-36257',
    authDomain: 'dice-master-36257.firebaseapp.com',
    storageBucket: 'dice-master-36257.firebasestorage.app',
    measurementId: 'G-6HVRREVKRJ',
  );
}
